import 'dotenv/config';
import { pool } from '../src/db/pool';

async function main(): Promise<void> {
  await pool.query(`
    ALTER TABLE vehicles
    ADD COLUMN IF NOT EXISTS image_url TEXT
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS saved_searches (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      search_text TEXT NOT NULL,
      filters JSONB,
      created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await pool.query(`
    CREATE INDEX IF NOT EXISTS saved_searches_user_id_idx
    ON saved_searches (user_id)
  `);

  // Optional demo photos by body type (safe public placeholders)
  await pool.query(`
    UPDATE vehicles
    SET image_url = CASE body_type
      WHEN 'suv' THEN 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80'
      WHEN 'sedan' THEN 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80'
      WHEN 'hatchback' THEN 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80'
      WHEN 'muv' THEN 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80'
      WHEN 'coupe' THEN 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80'
      WHEN 'convertible' THEN 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80'
      ELSE image_url
    END
    WHERE image_url IS NULL
  `);

  console.log('Migration complete: image_url + saved_searches');
  await pool.end();
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
