import { NextFunction, Response } from 'express';
import { pool } from '../db/pool';
import { AuthenticatedRequest } from '../middleware/authenticate';
import {
  advisorRequestSchema,
  generateVehicleAdvice
} from '../services/vehicleAdvisorService';

async function ensureAdvisorHistoryTable(): Promise<void> {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS ai_advisor_history (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      search_query TEXT NOT NULL DEFAULT '',
      filters JSONB NOT NULL,
      vehicle_ids JSONB NOT NULL,
      ai_response TEXT NOT NULL,
      created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);
}

export function createVehicleAdvisorController() {
  return {
    advise: async (
      request: AuthenticatedRequest,
      response: Response,
      next: NextFunction
    ): Promise<void> => {
      try {
        const input = advisorRequestSchema.parse(request.body);

        // Keep search page working even when Gemini is down.
        const advice = await generateVehicleAdvice(input);

        if (!advice) {
          response.json({
            advice: null,
            error: 'AI Advisor is currently unavailable.'
          });
          return;
        }

        // Optional: save for the logged-in user (JWT userId).
        if (request.userId) {
          try {
            await ensureAdvisorHistoryTable();
            await pool.query(
              `
                INSERT INTO ai_advisor_history
                  (user_id, search_query, filters, vehicle_ids, ai_response)
                VALUES ($1, $2, $3::jsonb, $4::jsonb, $5)
              `,
              [
                request.userId,
                input.query || '',
                JSON.stringify(input.filters),
                JSON.stringify(input.vehicles.map((vehicle) => vehicle.id)),
                advice
              ]
            );
          } catch {
            // History is secondary — never fail the advisor response.
          }
        }

        response.json({ advice });
      } catch (error: unknown) {
        next(error);
      }
    }
  };
}
