-- Run this script in pgAdmin4 Query Tool
-- Database: vehicle_search

CREATE TABLE IF NOT EXISTS vehicles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    make VARCHAR(50) NOT NULL,
    model VARCHAR(80) NOT NULL,
    variant VARCHAR(120) NOT NULL,
    year INTEGER NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    fuel_type VARCHAR(20) NOT NULL,
    transmission VARCHAR(20) NOT NULL,
    body_type VARCHAR(20) NOT NULL,
    km_driven INTEGER NOT NULL,
    safety_rating NUMERIC(2, 1) NOT NULL,
    seating_capacity INTEGER NOT NULL,
    mileage NUMERIC(5, 2) NOT NULL,
    city VARCHAR(50) NOT NULL,
    ownership INTEGER NOT NULL,
    image_url TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT vehicles_year_check
        CHECK (year BETWEEN 1990 AND 2030),
    CONSTRAINT vehicles_price_check
        CHECK (price >= 0),
    CONSTRAINT vehicles_fuel_type_check
        CHECK (fuel_type IN ('petrol', 'diesel', 'electric', 'hybrid', 'cng')),
    CONSTRAINT vehicles_transmission_check
        CHECK (transmission IN ('manual', 'automatic', 'amt', 'cvt', 'dct')),
    CONSTRAINT vehicles_body_type_check
        CHECK (body_type IN ('hatchback', 'sedan', 'suv', 'muv', 'coupe', 'convertible')),
    CONSTRAINT vehicles_km_driven_check
        CHECK (km_driven >= 0),
    CONSTRAINT vehicles_safety_rating_check
        CHECK (safety_rating BETWEEN 0 AND 5),
    CONSTRAINT vehicles_seating_capacity_check
        CHECK (seating_capacity BETWEEN 2 AND 12),
    CONSTRAINT vehicles_mileage_check
        CHECK (mileage >= 0),
    CONSTRAINT vehicles_ownership_check
        CHECK (ownership >= 1)
);

CREATE INDEX IF NOT EXISTS vehicles_price_idx
    ON vehicles (price);

CREATE INDEX IF NOT EXISTS vehicles_year_idx
    ON vehicles (year);

CREATE INDEX IF NOT EXISTS vehicles_city_body_type_idx
    ON vehicles (city, body_type);

CREATE INDEX IF NOT EXISTS vehicles_fuel_transmission_idx
    ON vehicles (fuel_type, transmission);

-- Confirm the table was created.
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_name = 'vehicles'
ORDER BY ordinal_position;
